@baseURL=http://localhost:8002/v1/2024/contest

###
POST {{baseURL}}/create
Authorization: Bearer v2.local.xJgAKiohSuCUKhDFz2TBOGLE3vbay_SLHUVv3lzVc3OUGQ6f2eGacDAHVrurACrlwlfikLw7fe29tLEnBstrqU184bnytt2MhN75dhjUxoncbLqzSwrIH4Cved1ZACEArqDWLllfepSCde6GLPHYdCm1rvz09Hn8MMD1VQHDMitGCJs1wxrJys0uTbx9Jd-cCEFzJrH-QMNDV7zVcJpQ77StTsDUooeMGUt7RpZYGSnSYrgweJNV0ds3syMESWw9aPgasLSStmvRLZlvTBEkYq6h9E15RojaSSM.bnVsbA
Content-Type: application/json

{
    "subject_id": 20, 
    "num_question": 12, 
    "time_exam": 3
}