@baseUrl=http://localhost:8002/v1/2024/user

### Register
POST {{baseUrl}}/register
Content-Type: application/json

{
    "email": "hoanghieuss3x10@gmail.com",
    "password": "test13435"
}

### Verify OTP
POST {{baseUrl}}/verify_otp
Content-Length: application/json

{
    "email": "hoanghieuss3x10@gmail.com",
    "otp": 123456
}

### Login
POST {{baseUrl}}/login
Content-Length: application/json

{
    "email": "hoanghieuss3x10@gmail.com",
    "password": "test13435"
}
### GetInfo
POST {{baseUrl}}/info
Content-Length: application/json

{
    "email": "hoanghieuss3x10@gmail.com",
    "password": "test13435"
}