server: 
  port : 8082
  mode: "dev"
mysql: 
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  dbname: shopdev
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
postgres:
  dbDriver: postgres
  dbSource: "postgresql://root:secret@localhost:5432/goBackend?sslmode=disable"
logger: 
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
redis: 
  host: localhost
  port: 6379
  password: U9vO5nr7tG3ECgoAy871PXL5I53oD9tE
token: 
  secret_key: "01234567890123456789012345678912"
  access_token_duration: 30m
  refresh_token_duration: 24h
imgur: 
  client_id: c73e3a75440ef9f
  client_secret: 29b45fc20eb0a236885c9c0f50db5a6e309cd519
imgbb:
  api_key: f2335b3f22806aa403a63b411d7fc6cd