server: 
  port : 8082
database: 
  - user: admin 
    password: admin
    host: localhost
    dbName: shopDEV
  - user: user 
    password: user
    host: localhost
    dbName: orderUser
security: 
  jwt: 
    key: abc123
